// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations run DDL and need a direct/session connection, not the
    // transaction-mode pooler (which DATABASE_URL points at for the app).
    url: process.env["DIRECT_URL"],
  },
});
